import type { PlantInput } from "./schema";
const plantsData: PlantInput[] = [
  {scientific_name: "Zelkova serrata", kr_name: "느티나무", life_form: "교목", max_height_m: 8.1, root_depth_cm_range: "95-147", light_requirement_1_5: 4, lifespan_yr: 116},
  {scientific_name: "Acer palmatum", kr_name: "단풍나무", life_form: "교목", max_height_m: 19.9, root_depth_cm_range: "112-154", light_requirement_1_5: 5, lifespan_yr: 101},
  {scientific_name: "Ginkgo biloba", kr_name: "은행나무", life_form: "교목", max_height_m: 15.0, root_depth_cm_range: "90-167", light_requirement_1_5: 4, lifespan_yr: 69},
  {scientific_name: "Pinus densiflora", kr_name: "소나무", life_form: "교목", max_height_m: 13.3, root_depth_cm_range: "108-150", light_requirement_1_5: 5, lifespan_yr: 83},
  {scientific_name: "Platanus × hispanica", kr_name: "양버즘나무", life_form: "교목", max_height_m: 9.9, root_depth_cm_range: "113-164", light_requirement_1_5: 4, lifespan_yr: 97},
  {scientific_name: "Prunus yedoensis", kr_name: "왕벚나무", life_form: "교목", max_height_m: 9.5, root_depth_cm_range: "86-133", light_requirement_1_5: 4, lifespan_yr: 100},
  {scientific_name: "Metasequoia glyptostroboides", kr_name: "메타세쿼이아", life_form: "교목", max_height_m: 13.3, root_depth_cm_range: "87-150", light_requirement_1_5: 4, lifespan_yr: 92},
  {scientific_name: "Quercus acutissima", kr_name: "갈참나무", life_form: "교목", max_height_m: 10.8, root_depth_cm_range: "103-146", light_requirement_1_5: 5, lifespan_yr: 71},
  {scientific_name: "Betula platyphylla var. japonica", kr_name: "자작나무", life_form: "교목", max_height_m: 17.4, root_depth_cm_range: "115-161", light_requirement_1_5: 4, lifespan_yr: 62},
  {scientific_name: "Celtis sinensis", kr_name: "팽나무", life_form: "교목", max_height_m: 12.3, root_depth_cm_range: "119-188", light_requirement_1_5: 3, lifespan_yr: 78},
  {scientific_name: "Koelreuteria paniculata", kr_name: "칠엽수", life_form: "교목", max_height_m: 19.6, root_depth_cm_range: "85-135", light_requirement_1_5: 5, lifespan_yr: 106},
  {scientific_name: "Magnolia kobus", kr_name: "목련", life_form: "교목", max_height_m: 14.8, root_depth_cm_range: "81-126", light_requirement_1_5: 5, lifespan_yr: 97},
  {scientific_name: "Sophora japonica", kr_name: "회화나무", life_form: "교목", max_height_m: 17.0, root_depth_cm_range: "87-154", light_requirement_1_5: 4, lifespan_yr: 74},
  {scientific_name: "Salix babylonica", kr_name: "수양버들", life_form: "교목", max_height_m: 9.1, root_depth_cm_range: "105-183", light_requirement_1_5: 5, lifespan_yr: 87},
  {scientific_name: "Lagerstroemia indica", kr_name: "배롱나무", life_form: "교목", max_height_m: 10.6, root_depth_cm_range: "106-149", light_requirement_1_5: 3, lifespan_yr: 74},
  {scientific_name: "Albizia julibrissin", kr_name: "자귀나무", life_form: "교목", max_height_m: 11.7, root_depth_cm_range: "92-146", light_requirement_1_5: 4, lifespan_yr: 83},
  {scientific_name: "Chionanthus retusus", kr_name: "이팝나무", life_form: "교목", max_height_m: 10.5, root_depth_cm_range: "108-181", light_requirement_1_5: 3, lifespan_yr: 100},
  {scientific_name: "Cornus controversa", kr_name: "층층나무", life_form: "교목", max_height_m: 11.1, root_depth_cm_range: "81-134", light_requirement_1_5: 4, lifespan_yr: 116},
  {scientific_name: "Cornus kousa", kr_name: "산딸나무", life_form: "교목", max_height_m: 11.7, root_depth_cm_range: "118-177", light_requirement_1_5: 3, lifespan_yr: 98},
  {scientific_name: "Pyrus pyrifolia", kr_name: "배나무", life_form: "교목", max_height_m: 8.7, root_depth_cm_range: "89-141", light_requirement_1_5: 4, lifespan_yr: 111},
  {scientific_name: "Aesculus turbinata", kr_name: "칠엽수", life_form: "교목", max_height_m: 15.5, root_depth_cm_range: "103-171", light_requirement_1_5: 5, lifespan_yr: 90},
  {scientific_name: "Thuja occidentalis", kr_name: "양측백나무", life_form: "교목", max_height_m: 13.4, root_depth_cm_range: "95-147", light_requirement_1_5: 4, lifespan_yr: 77},
  {scientific_name: "Taxus cuspidata", kr_name: "주목", life_form: "교목", max_height_m: 11.5, root_depth_cm_range: "117-160", light_requirement_1_5: 4, lifespan_yr: 92},
  {scientific_name: "Spiraea japonica", kr_name: "조팝나무", life_form: "관목", max_height_m: 2.3, root_depth_cm_range: "63-83", light_requirement_1_5: 3, lifespan_yr: 26},
  {scientific_name: "Forsythia koreana", kr_name: "개나리", life_form: "관목", max_height_m: 1.0, root_depth_cm_range: "46-73", light_requirement_1_5: 3, lifespan_yr: 21},
  {scientific_name: "Hibiscus syriacus", kr_name: "무궁화", life_form: "관목", max_height_m: 3.6, root_depth_cm_range: "45-84", light_requirement_1_5: 4, lifespan_yr: 39},
  {scientific_name: "Rosa rugosa", kr_name: "해변장미", life_form: "관목", max_height_m: 2.0, root_depth_cm_range: "55-81", light_requirement_1_5: 4, lifespan_yr: 34},
  {scientific_name: "Buddleja davidii", kr_name: "부들레야", life_form: "관목", max_height_m: 3.3, root_depth_cm_range: "49-80", light_requirement_1_5: 5, lifespan_yr: 42},
  {scientific_name: "Hydrangea macrophylla", kr_name: "수국", life_form: "관목", max_height_m: 3.7, root_depth_cm_range: "66-97", light_requirement_1_5: 5, lifespan_yr: 35},
  {scientific_name: "Camellia japonica", kr_name: "동백나무", life_form: "관목", max_height_m: 2.3, root_depth_cm_range: "67-88", light_requirement_1_5: 3, lifespan_yr: 50},
  {scientific_name: "Rhododendron mucronulatum", kr_name: "진달래", life_form: "관목", max_height_m: 4.0, root_depth_cm_range: "41-73", light_requirement_1_5: 5, lifespan_yr: 31},
  {scientific_name: "Gardenia jasminoides", kr_name: "치자나무", life_form: "관목", max_height_m: 3.6, root_depth_cm_range: "40-79", light_requirement_1_5: 5, lifespan_yr: 26},
  {scientific_name: "Buxus microphylla", kr_name: "회양목", life_form: "관목", max_height_m: 2.8, root_depth_cm_range: "70-98", light_requirement_1_5: 3, lifespan_yr: 22},
  {scientific_name: "Nandina domestica", kr_name: "남천", life_form: "관목", max_height_m: 1.0, root_depth_cm_range: "68-95", light_requirement_1_5: 5, lifespan_yr: 31},
  {scientific_name: "Euonymus alatus", kr_name: "화살나무", life_form: "관목", max_height_m: 3.4, root_depth_cm_range: "54-85", light_requirement_1_5: 3, lifespan_yr: 43},
  {scientific_name: "Deutzia gracilis", kr_name: "말발도리", life_form: "관목", max_height_m: 2.7, root_depth_cm_range: "43-68", light_requirement_1_5: 4, lifespan_yr: 27},
  {scientific_name: "Syringa vulgaris", kr_name: "라일락", life_form: "관목", max_height_m: 2.7, root_depth_cm_range: "58-94", light_requirement_1_5: 4, lifespan_yr: 24},
  {scientific_name: "Osmanthus fragrans", kr_name: "금목서", life_form: "관목", max_height_m: 1.9, root_depth_cm_range: "50-76", light_requirement_1_5: 4, lifespan_yr: 24},
  {scientific_name: "Berberis thunbergii", kr_name: "매자나무", life_form: "관목", max_height_m: 2.5, root_depth_cm_range: "53-93", light_requirement_1_5: 5, lifespan_yr: 24},
  {scientific_name: "Mahonia aquifolium", kr_name: "마호니아", life_form: "관목", max_height_m: 2.1, root_depth_cm_range: "51-86", light_requirement_1_5: 4, lifespan_yr: 37},
  {scientific_name: "Viburnum plicatum", kr_name: "불두화", life_form: "관목", max_height_m: 2.5, root_depth_cm_range: "45-70", light_requirement_1_5: 5, lifespan_yr: 25},
  {scientific_name: "Azalea indica", kr_name: "철쭉", life_form: "관목", max_height_m: 1.2, root_depth_cm_range: "41-74", light_requirement_1_5: 5, lifespan_yr: 47},
  {scientific_name: "Philadelphus coronarius", kr_name: "팥배나무", life_form: "관목", max_height_m: 2.7, root_depth_cm_range: "41-78", light_requirement_1_5: 4, lifespan_yr: 46},
  {scientific_name: "Daphne odora", kr_name: "영춘화", life_form: "관목", max_height_m: 3.5, root_depth_cm_range: "53-85", light_requirement_1_5: 4, lifespan_yr: 28},
  {scientific_name: "Lavandula angustifolia", kr_name: "라벤더", life_form: "초화", max_height_m: 0.94, root_depth_cm_range: "25-39", light_requirement_1_5: 2, lifespan_yr: 8},
  {scientific_name: "Hemerocallis fulva", kr_name: "큰꽃원추리", life_form: "초화", max_height_m: 0.69, root_depth_cm_range: "15-27", light_requirement_1_5: 5, lifespan_yr: 10},
  {scientific_name: "Miscanthus sinensis", kr_name: "억새", life_form: "초화", max_height_m: 0.86, root_depth_cm_range: "18-26", light_requirement_1_5: 2, lifespan_yr: 3},
  {scientific_name: "Pennisetum alopecuroides", kr_name: "왕쥐꼬리새", life_form: "초화", max_height_m: 1.14, root_depth_cm_range: "18-30", light_requirement_1_5: 5, lifespan_yr: 4},
  {scientific_name: "Carex oshimensis", kr_name: "왕사초", life_form: "초화", max_height_m: 0.71, root_depth_cm_range: "21-33", light_requirement_1_5: 2, lifespan_yr: 8},
  {scientific_name: "Liriope muscari", kr_name: "맥문동", life_form: "초화", max_height_m: 0.3, root_depth_cm_range: "18-25", light_requirement_1_5: 3, lifespan_yr: 4},
  {scientific_name: "Pachysandra terminalis", kr_name: "차전초", life_form: "초화", max_height_m: 0.56, root_depth_cm_range: "17-23", light_requirement_1_5: 5, lifespan_yr: 3},
  {scientific_name: "Vinca minor", kr_name: "비카", life_form: "초화", max_height_m: 0.58, root_depth_cm_range: "17-26", light_requirement_1_5: 3, lifespan_yr: 4},
  {scientific_name: "Hosta plantaginea", kr_name: "옥잠화", life_form: "초화", max_height_m: 0.82, root_depth_cm_range: "18-23", light_requirement_1_5: 3, lifespan_yr: 7},
  {scientific_name: "Iris ensata", kr_name: "꽃창포", life_form: "초화", max_height_m: 1.2, root_depth_cm_range: "25-37", light_requirement_1_5: 5, lifespan_yr: 3},
  {scientific_name: "Sedum kamtschaticum", kr_name: "기린초", life_form: "초화", max_height_m: 0.55, root_depth_cm_range: "16-23", light_requirement_1_5: 2, lifespan_yr: 9},
  {scientific_name: "Coreopsis verticillata", kr_name: "금계국", life_form: "초화", max_height_m: 0.2, root_depth_cm_range: "16-29", light_requirement_1_5: 3, lifespan_yr: 4},
  {scientific_name: "Rudbeckia hirta", kr_name: "루드베키아", life_form: "초화", max_height_m: 0.57, root_depth_cm_range: "11-26", light_requirement_1_5: 3, lifespan_yr: 9},
  {scientific_name: "Echinacea purpurea", kr_name: "에키네시아", life_form: "초화", max_height_m: 0.52, root_depth_cm_range: "16-28", light_requirement_1_5: 5, lifespan_yr: 7},
  {scientific_name: "Nepeta cataria", kr_name: "캣닢", life_form: "초화", max_height_m: 0.8, root_depth_cm_range: "10-22", light_requirement_1_5: 2, lifespan_yr: 8},
  {scientific_name: "Miscanthus sacchariflorus", kr_name: "갈대", life_form: "초화", max_height_m: 0.29, root_depth_cm_range: "17-32", light_requirement_1_5: 4, lifespan_yr: 8},
  {scientific_name: "Hakonechloa macra", kr_name: "하코네참억새", life_form: "초화", max_height_m: 0.78, root_depth_cm_range: "23-31", light_requirement_1_5: 5, lifespan_yr: 7},
  {scientific_name: "Salvia splendens", kr_name: "샐비어", life_form: "초화", max_height_m: 0.86, root_depth_cm_range: "20-34", light_requirement_1_5: 2, lifespan_yr: 5},
  {scientific_name: "Pennisetum setaceum 'Rubrum'", kr_name: "핑크뮬리", life_form: "초화", max_height_m: 0.32, root_depth_cm_range: "15-26", light_requirement_1_5: 5, lifespan_yr: 5},
  {scientific_name: "Ophiopogon japonicus", kr_name: "자주감초", life_form: "초화", max_height_m: 0.31, root_depth_cm_range: "23-38", light_requirement_1_5: 4, lifespan_yr: 7},
  {scientific_name: "Festuca glauca", kr_name: "푸른김잔디", life_form: "초화", max_height_m: 0.24, root_depth_cm_range: "16-24", light_requirement_1_5: 4, lifespan_yr: 8},
  {scientific_name: "Agapanthus africanus", kr_name: "아가판서스", life_form: "초화", max_height_m: 0.28, root_depth_cm_range: "17-29", light_requirement_1_5: 4, lifespan_yr: 4},
  {scientific_name: "Gaura lindheimeri", kr_name: "가우라", life_form: "초화", max_height_m: 0.71, root_depth_cm_range: "20-28", light_requirement_1_5: 2, lifespan_yr: 5},
  {scientific_name: "Alchemilla mollis", kr_name: "알케밀라", life_form: "초화", max_height_m: 1.12, root_depth_cm_range: "17-27", light_requirement_1_5: 5, lifespan_yr: 6},
  {scientific_name: "Ajuga reptans", kr_name: "아주가", life_form: "초화", max_height_m: 0.89, root_depth_cm_range: "23-36", light_requirement_1_5: 2, lifespan_yr: 8},
  {scientific_name: "Geranium sanguineum", kr_name: "제라늄", life_form: "초화", max_height_m: 0.56, root_depth_cm_range: "10-17", light_requirement_1_5: 5, lifespan_yr: 9},
  {scientific_name: "Ornithogalum umbellatum", kr_name: "별수선", life_form: "초화", max_height_m: 0.32, root_depth_cm_range: "21-31", light_requirement_1_5: 4, lifespan_yr: 10},
  {scientific_name: "Crocosmia aurea", kr_name: "크로코스미아", life_form: "초화", max_height_m: 0.97, root_depth_cm_range: "11-17", light_requirement_1_5: 4, lifespan_yr: 9},
  {scientific_name: "Persicaria affinis", kr_name: "범꼬리", life_form: "초화", max_height_m: 1.14, root_depth_cm_range: "11-19", light_requirement_1_5: 4, lifespan_yr: 9},
  {scientific_name: "Phlox subulata", kr_name: "플록스", life_form: "초화", max_height_m: 1.01, root_depth_cm_range: "25-33", light_requirement_1_5: 3, lifespan_yr: 4},
  {scientific_name: "Hylotelephium telephium", kr_name: "돌나물", life_form: "초화", max_height_m: 0.99, root_depth_cm_range: "13-24", light_requirement_1_5: 2, lifespan_yr: 3},
  {scientific_name: "Achillea millefolium", kr_name: "서양톱풀", life_form: "초화", max_height_m: 1.14, root_depth_cm_range: "19-27", light_requirement_1_5: 3, lifespan_yr: 5},
  {scientific_name: "Digitalis purpurea", kr_name: "디지털리스", life_form: "초화", max_height_m: 1.04, root_depth_cm_range: "21-27", light_requirement_1_5: 2, lifespan_yr: 8},
  {scientific_name: "Campanula carpatica", kr_name: "캄파눌라", life_form: "초화", max_height_m: 1.08, root_depth_cm_range: "21-31", light_requirement_1_5: 5, lifespan_yr: 8},
  {scientific_name: "Dianthus barbatus", kr_name: "스위트윌리엄", life_form: "초화", max_height_m: 0.27, root_depth_cm_range: "18-25", light_requirement_1_5: 5, lifespan_yr: 10},
  {scientific_name: "Heuchera sanguinea", kr_name: "휴케라", life_form: "초화", max_height_m: 0.36, root_depth_cm_range: "20-29", light_requirement_1_5: 5, lifespan_yr: 7},
  {scientific_name: "Astilbe japonica", kr_name: "아스틸베", life_form: "초화", max_height_m: 0.49, root_depth_cm_range: "20-34", light_requirement_1_5: 3, lifespan_yr: 6},
  {scientific_name: "Aquilegia flabellata", kr_name: "매발톱", life_form: "초화", max_height_m: 0.25, root_depth_cm_range: "17-25", light_requirement_1_5: 2, lifespan_yr: 5},
  {scientific_name: "Brunnera macrophylla", kr_name: "브루네라", life_form: "초화", max_height_m: 0.72, root_depth_cm_range: "20-28", light_requirement_1_5: 2, lifespan_yr: 7},
  {scientific_name: "Bergenia cordifolia", kr_name: "베르게니아", life_form: "초화", max_height_m: 0.48, root_depth_cm_range: "13-22", light_requirement_1_5: 4, lifespan_yr: 4},
  {scientific_name: "Nepeta × faassenii", kr_name: "네페타", life_form: "초화", max_height_m: 1.08, root_depth_cm_range: "25-38", light_requirement_1_5: 4, lifespan_yr: 10},
  {scientific_name: "Eryngium planum", kr_name: "에린지움", life_form: "초화", max_height_m: 0.9, root_depth_cm_range: "14-28", light_requirement_1_5: 5, lifespan_yr: 6},
  {scientific_name: "Gaillardia aristata", kr_name: "가일라르디아", life_form: "초화", max_height_m: 0.52, root_depth_cm_range: "25-38", light_requirement_1_5: 5, lifespan_yr: 4},
  {scientific_name: "Chrysanthemum × morifolium", kr_name: "국화", life_form: "초화", max_height_m: 1.18, root_depth_cm_range: "16-23", light_requirement_1_5: 5, lifespan_yr: 5},
  {scientific_name: "Anthemis tinctoria", kr_name: "카밀레", life_form: "초화", max_height_m: 1.07, root_depth_cm_range: "20-28", light_requirement_1_5: 5, lifespan_yr: 10},
  {scientific_name: "Penstemon digitalis", kr_name: "펜스테몬", life_form: "초화", max_height_m: 0.89, root_depth_cm_range: "24-31", light_requirement_1_5: 4, lifespan_yr: 8},
  {scientific_name: "Calamagrostis acutiflora", kr_name: "칼라마그로스티스", life_form: "초화", max_height_m: 1.09, root_depth_cm_range: "21-26", light_requirement_1_5: 2, lifespan_yr: 5},
  {scientific_name: "Molinia caerulea", kr_name: "모리니아", life_form: "초화", max_height_m: 0.82, root_depth_cm_range: "18-33", light_requirement_1_5: 4, lifespan_yr: 6},
  {scientific_name: "Carex morrowii", kr_name: "모로윗사초", life_form: "초화", max_height_m: 1.16, root_depth_cm_range: "17-30", light_requirement_1_5: 4, lifespan_yr: 8},
  {scientific_name: "Acorus gramineus 'Variegatus'", kr_name: "줄", life_form: "초화", max_height_m: 0.43, root_depth_cm_range: "11-23", light_requirement_1_5: 2, lifespan_yr: 7},
  {scientific_name: "Imperata cylindrica 'Red Baron'", kr_name: "일본피", life_form: "초화", max_height_m: 0.27, root_depth_cm_range: "23-31", light_requirement_1_5: 5, lifespan_yr: 10},
  {scientific_name: "Schizachyrium scoparium", kr_name: "스키자키리움", life_form: "초화", max_height_m: 0.8, root_depth_cm_range: "25-31", light_requirement_1_5: 2, lifespan_yr: 3},
  {scientific_name: "Panicum virgatum", kr_name: "스위치그래스", life_form: "초화", max_height_m: 0.23, root_depth_cm_range: "13-25", light_requirement_1_5: 4, lifespan_yr: 9},
  {scientific_name: "Miscanthus × giganteus", kr_name: "자이언트억새", life_form: "초화", max_height_m: 0.94, root_depth_cm_range: "25-34", light_requirement_1_5: 3, lifespan_yr: 8},
  {scientific_name: "Acer ginnala", kr_name: "신나무", life_form: "교목", max_height_m: 12.0, root_depth_cm_range: "80-120", light_requirement_1_5: 4, lifespan_yr: 80},
  {scientific_name: "Viburnum opulus", kr_name: "서양댕강나무", life_form: "관목", max_height_m: 2.8, root_depth_cm_range: "40-70", light_requirement_1_5: 3, lifespan_yr: 25}
];
export default plantsData;
